<?php
/**
 * Created by PhpStorm.
 * Eleve: Poizon
 * Date: 18/11/2015
 * Time: 14:02
 */

namespace Projet\Model;


class StringHelper {

    public static $tabLesPays = [
        "Afghanistan",
        "Afrique Centrale",
        "Afrique du sud",
        "Albanie",
        "Algerie",
        "Allemagne",
        "Andorre",
        "Angola",
        "Anguilla",
        "Arabie Saoudite",
        "Argentine",
        "Armenie",
        "Australie",
        "Autriche",
        "Azerbaidjan",

        "Bahamas",
        "Bangladesh",
        "Barbade",
        "Bahrein",
        "Belgique",
        "Belize",
        "Benin",
        "Bermudes",
        "Bielorussie",
        "Bolivie",
        "Botswana",
        "Bhoutan",
        "Boznie Herzegovine",
        "Bresil",
        "Brunei",
        "Bulgarie",
        "Burkina Faso",
        "Burundi",

        "Caiman",
        "Cambodge",
        "Cameroun",
        "Canada",
        "Canaries",
        "Cap vert",
        "Chili",
        "Chine",
        "Chypre",
        "Colombie",
        "Comores",
        "Congo",
        "Congo democratique",
        "Cook",
        "Coree du Nord",
        "Coree du Sud",
        "Costa Rica",
        "Cote d'Ivoire",
        "Croatie",
        "Cuba",

        "Danemark",
        "Djibouti",
        "Dominique",

        "Egypte",
        "Emirats Arabes Unis",
        "Equateur",
        "Erythree",
        "Espagne",
        "Estonie",
        "Etats Unis",
        "Ethiopie",

        "Falkland",
        "Feroe",
        "Fidji",
        "Finlande",
        "France",

        "Gabon",
        "Gambie",
        "Georgie",
        "Ghana",
        "Gibraltar",
        "Grece",
        "Grenade",
        "Groenland",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernesey",
        "Guinee",
        "Guinee Bissau",
        "Guinee equatoriale",
        "Guyana",
        "Guyane Francaise ",

        "Haiti",
        "Hawaii",
        "Honduras",
        "Hong Kong",
        "Hongrie",

        "Inde",
        "Indonesie",
        "Iran",
        "Iraq",
        "Irlande",
        "Islande",
        "Israel",
        "Italie",

        "Jamaique",
        "Jan Mayen",
        "Japon",
        "Jersey",
        "Jordanie",

        "Kazakhstan",
        "Kenya",
        "Kirghizstan",
        "Kiribati",
        "Koweit",

        "Laos",
        "Lesotho",
        "Lettonie",
        "Liban",
        "Liberia",
        "Liechtenstein",
        "Lituanie",
        "Luxembourg",
        "Lybie",

        "Maroc",
        "Macedoine",
        "Madagascar",
        "Madère",
        "Malaisie",
        "Malawi",
        "Maldives",
        "Mali",
        "Malte",
        "Man",
        "Mariannes du Nord",
        "Maroc",
        "Marshall",
        "Martinique",
        "Maurice",
        "Mauritanie",
        "Mayotte",
        "Mexique",
        "Micronesie",
        "Midway",
        "Moldavie",
        "Monaco",
        "Mongolie",
        "Montserrat",
        "Mozambique",

        "Namibie",
        "Nauru",
        "Nepal",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk",
        "Norvege",
        "Nouvelle Caledonie",
        "Nouvelle Zelande",

        "Oman",
        "Ouganda",
        "Ouzbekistan","Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papouasie Nouvelle Guinee",
        "Paraguay",
        "Pays Bas",
        "Perou",
        "Philippines",
        "Pologne",
        "Polynesie",
        "Porto Rico",
        "Portugal",

        "Qatar",

        "Republique Dominicaine",
        "Republique Tcheque",
        "Reunion",
        "Roumanie",
        "Royaume Uni",
        "Russie",
        "Rwanda",

        "Sahara Occidental",
        "Sainte Lucie",
        "Saint Marin",
        "Salomon",
        "Salvador",
        "Samoa Occidentales",
        "Samoa Americaine",
        "Sao Tome et Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Singapour",
        "Slovaquie",
        "Slovenie",
        "Somalie",
        "Soudan",
        "Sri Lanka",
        "Suede",
        "Suisse",
        "Surinam",
        "Swaziland",
        "Syrie",

        "Tadjikistan",
        "Taiwan",
        "Tonga",
        "Tanzanie",
        "Tchad",
        "Thailande",
        "Tibet",
        "Timor Oriental",
        "Togo",
        "Trinite et Tobago",
        "Tristan da cunha",
        "Tunisie",
        "Turkmenistan",
        "Turquie",

        "Ukraine",
        "Uruguay",

        "Vanuatu",
        "Vatican",
        "Venezuela",
        "Vierges Americaines",
        "Vierges Britanniques",
        "Vietnam",

        "Wake",
        "Wallis et Futuma",

        "Yemen",
        "Yougoslavie",

        "Zambie",
        "Zimbabwe"
    ];

    public static $categorie= [

        "1"=>"CDI",
        "2"=>"CDD",
        "3"=>"Freelance",
        "4"=>"Stage",
        "5"=>"Temporaire"
    ];

    public static $secteurActivite = [
      "Administration & Gestion",
      "Agriculture/Agro-Industrie",
      "Autre Emplois",
      "Commmunication/Rédaction",
      "Comptabilité/Finance",
      "Design, Art & Multimedia",
      "Electricité/Electronique",
      "Enseignement/Formation",
      "Habillement/Mode/Hôtesse",
      "Hôtellerie/Restauration",
      "Informatique/Internet",
      "Juridique",
      "Marketing et Vente",
      "Mécanique/Electromécanique",
      "Métiers des services",
      "Métiers du BTP",
      "RH",
      "Santé & Médécine",
      "Secrétariat/Assistance",
      "Sécurité",
      "Services Domestique",
      "Transport et Logistique"
    ];

    public static $reponse = [
      '0' => '<span class="badge badge-success">Accepté</span>',
      '1' => '<span class="badge badge-warning">Refusé</span>',
      '2' => '<span class="badge badge-info">Attente</span>'
    ];


}